-- История задач
CREATE TABLE IF NOT EXISTS task_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  task_id BIGINT NOT NULL,
  subtask_id BIGINT,
  change_type TEXT NOT NULL,
  changed_at DATE NOT NULL,
  order_index INTEGER DEFAULT 0,
  task_title TEXT NOT NULL,
  task_path TEXT,
  new_status TEXT,
  new_priority TEXT,
  new_assignees TEXT
);

-- Индекс для сортировки
CREATE INDEX IF NOT EXISTS idx_task_history_changed_at ON task_history(changed_at DESC, order_index ASC);
CREATE INDEX IF NOT EXISTS idx_task_history_task_id ON task_history(task_id);